name: Main Workflow

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    timeout-minutes: 30
    runs-on:
      - self-hosted
      - nix
      - general
      - ${{ matrix.runner.runner }}
      - ${{ matrix.runner.size }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - arch: x86_64-linux
            runner: amd64-linux
            size: max
          - arch: aarch64-linux
            runner: arm64-linux
            size: max
          - arch: aarch64-darwin
            runner: arm64-darwin
            size: small
    env:
      NIX_OUTPUT: ".#packages.${{ matrix.runner.arch }}.fdb_7.all"
    steps:
      - uses: actions/checkout@v4

      - name: Info
        run: |
          nix show-derivation '.#defaultPackage.${{ matrix.runner.arch }}'
          nix path-info '.#defaultPackage.${{ matrix.runner.arch }}' || true

      - name: Build
        run: |
          nix build -L -v --no-link "${NIX_OUTPUT}"

      - name: Cache
        run: |
          nix store sign "${NIX_OUTPUT}" -v -r -k ~/.secrets/nix-cache-private-key
          nix copy -v --to "s3://${NIX_CACHE_BUCKET_NAME}/cache?region=${NIX_CACHE_BUCKET_REGION}&compression=zstd&parallel-compression=true" "${NIX_OUTPUT}"
