name: Main Workflow

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64-linux
          - x86_64-darwin
          - aarch64-linux
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup
        uses: shopstic/tailscale-nix-builder/setup@494e27520e3bbcd48d1d7fadc3c4538dd8838bef
        timeout-minutes: 1
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          nixCacheS3AccessKeyId: ${{ secrets.NIX_CACHE_S3_ACCESS_KEY_ID }}
          nixCacheS3SecretAccessKey: ${{ secrets.NIX_CACHE_S3_SECRET_ACCESS_KEY }}
          # nixBuilders: ec2-user@nix-graviton-builder.shopstic.org.github.beta.tailscale.net aarch64-linux; root@nix-x86-64-darwin.shopstic.org.github.beta.tailscale.net x86_64-darwin;

      - name: Info
        run: |
          nix show-derivation '.#defaultPackage.${{ matrix.arch }}'
          nix path-info '.#defaultPackage.${{ matrix.arch }}' || true

      - name: Build
        run: nix build -L -v --no-link '.#defaultPackage.${{ matrix.arch }}'

      - name: Cache
        uses: shopstic/tailscale-nix-builder/cache@494e27520e3bbcd48d1d7fadc3c4538dd8838bef
        with:
          nixOutput: .#defaultPackage.${{ matrix.arch }}
          nixCachePrivateKey: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
